trigger: none

pool: raj-pool

variables:
  path: '$(System.DefaultWorkingDirectory)/Module'
  service-connection: 'raj-service'

steps:


# Terraform Init
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: $(path)
    backendServiceArm: '$(service-connection)'
    backendAzureRmResourceGroupName: 'raj-kumar-snatoshi'
    backendAzureRmStorageAccountName: 'rajkastorage1123'
    backendAzureRmContainerName: 'raj-dbba'
    backendAzureRmKey: 'dabba.tfstate'

# Terraform Plan
- task: TerraformTask@5
  displayName: 'Terraform Plan'
  name: terraformPlan  
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(path)
    environmentServiceNameAzureRM: $(service-connection)

# Optional manual approval
# - task: ManualValidation@1
#   displayName: '🛑 Manual Approval Before Apply'
#   condition: succeeded('terraformPlan')
#   timeoutInMinutes: 60
#   inputs:
#     instructions: 'Review Terraform plan and approve to continue.'
#     notifyUsers: 'abhay.kumar.singh11sep@gmail.com'
#     onTimeout: 'reject'

# Terraform Apply
- task: TerraformTask@5
  displayName: 'Terraform Apply'
  condition: succeeded()
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: $(path)
    environmentServiceNameAzureRM: $(service-connection)
    args: '-auto-approve'
