trigger: none

pool: raj-pool

variables:
  path: '$(System.DefaultWorkingDirectory)/Module'
  service-connection: 'raj-service'

steps:
- task: TerraformInstaller@1
  displayName: 'Terraform install' 
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Pipeline-service-connection'
    backendAzureRmResourceGroupName: 'abhay-rg'
    backendAzureRmStorageAccountName: 'abhaypipelinestorage1234'
    backendAzureRmContainerName: 'newcontainer'
    backendAzureRmKey: 'terraform.tfstate'
