trigger: none
pool: raj-pool

steps:
- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
    backendServiceArm: 'raj-service'
    backendAzureRmResourceGroupName: 'raj-kumar-snatoshi'
    backendAzureRmStorageAccountName: 'rajkastorage1123'
    backendAzureRmContainerName: 'raj-dbba'
    backendAzureRmKey: 'dabba.tfstate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
    environmentServiceNameAzureRM: 'raj-service'

- task: TerraformTask@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Module'
    environmentServiceNameAzureRM: 'raj-service'
    args: '-auto-approve'
